[profile.default]
solc = "0.8.25"

src = "src"
out = "out"
libs = ["lib"]
ffi = true
gas_limit = 1073741824
gas_price = 0

# The default is to optimise, but let's be clear about it.
optimizer = true
optimizer_runs = 10_000



remappings = [
    'src/=src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/ds-test/src/',
    '@prb/test/=lib/prb-test/src/',

]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

#[dependencies]
#    "openzeppelin-contracts", "@openzeppelin-contracts" = { version = "5.0.2" }
#    "forge-std"

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
wrap_comments = true

[profile.deployment]
# 
sepolia-rpc = "https://worldchain-sepolia.g.alchemy.com/public"
